### ISSUE TITLE
Livestream from PC or RPI

### ISSUE THREAD

**Issue by oaf2015** [KonradIT/gopro-control#2]
When I input 10.5.5.9:8080 I only have three options. Is there a way to stream what the go pro sees without actually recording? I appreciate your help.

**Comment by KonradIT** [comment]
What GoPro camera do you have?

**Comment by oaf2015** [comment]
3, 3+, and 4. But specifically referring to the 3+.

**Comment by oaf2015** [comment]
??

**Comment by KonradIT** [comment]
https://github.com/KonradIT/goprowifihack/blob/master/HERO3/Livestreaming.md
